name: CI

on:
  push:
    branches: [ master, develop, pyqt5_version_test ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    name: build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3

    - uses: conda-incubator/setup-miniconda@v2.0.0
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}

    - name: Install requirements
      shell: bash -l {0}
      run: |
        conda activate test
        pip install --requirement requirements.txt
